services:
  prometheus:
    build:
      context:  ./prometheus
    container_name: prometheus
    restart: unless-stopped
    environment:
      - PROMETHEUS_LOG_LEVEL=info
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus-data:/prometheus:rw
    networks:
      - monitoring_network
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.config.file=/etc/prometheus/web.yml'
      - '--storage.tsdb.retention.time=15d'
      - '--web.listen-address=:9090'

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=dodskorpen
      - GF_SECURITY_ADMIN_PASSWORD=d2ba87029450050d18618d7af55becf6b03aedda99a4171272bfa190b9cbf76a
      - GF_SERVER_HTTP_PORT=3000
      - GF_LOG_LEVEL=debug
      - GF_DATABASE_TYPE=sqlite3
      - GF_AUTH_BASIC_ENABLED=true
      - GF_AUTH_ANONIMOUS_ENABLED=false
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana:rw
    networks:
      - monitoring_network
    depends_on:
      - prometheus

volumes:
  grafana-data:
    driver: local
  prometheus-data:
    driver: local

networks:
    monitoring_network:
